#!/usr/bin/env bash
#SBATCH --job-name=train_model          # Job name
#SBATCH --nodes=2
#SBATCH --ntasks=2                      # Number of MPI tasks to request
#SBATCH --cpus-per-task=1               # Number of CPU cores per MPI task
#SBATCH --mem=8G                       # Total memory to request
#SBATCH --time=0-1:00:00                # Time limit (DD-HH:MM:SS)
#SBATCH --account=CS-ANIMALNN-2020      # Project account to use
#SBATCH --mail-type=ALL                 # Mail events (NONE, BEGIN, END, FAIL, ALL)
#SBATCH --mail-user=vpc511@york.ac.uk   # Where to send mail
#SBATCH --output=%x-%j.log              # Standard output log
#SBATCH --error=%x-%j.err               # Standard error log
#SBATCH --partition=gpu
#SBATCH --gres=gpu:2

# Abort if any command fails
set -e

# purge any existing modules
module purge

# Load modules
module load Python/3.12.3-GCCcore-13.3.0

# Commands to run
cd scratch/Breast-US-Mammo-Classifier
source torch-venv/bin/activate
python main.py
