#!/usr/bin/env bash
#SBATCH --job-name=train_model
#SBATCH --partition=gpu
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --gres=gpu:3
#SBATCH --exclusive
#SBATCH --cpus-per-task=1
#SBATCH --mem=16G
#SBATCH --time=0-1:00:00
#SBATCH --account=CS-ANIMALNN-2020
#SBATCH --output=%x-%j.log
#SBATCH --error=%x-%j.err
#SBATCH --mail-type=ALL
#SBATCH --mail-user=vpc511@york.ac.uk

set -e
module purge
module load Python/3.12.3-GCCcore-13.3.0

cd scratch/Breast-US-Mammo-Classifier
source torch-venv/bin/activate

export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK

echo "CUDA_VISIBLE_DEVICES=$CUDA_VISIBLE_DEVICES"
nvidia-smi

torchrun \
  --nproc_per_node=$SLURM_GPUS_ON_NODE \
  main.py
